/**
 * Block ids and the Ruderal Futurism palette.
 *
 * Palette rules (see plan §4): substrate desaturated, life saturated but
 * narrow-band, and marigold amber is RESERVED for player agency — nothing
 * generated by the world may use it.
 */

export const Block = {
  Air: 0,
  Soil: 1,
  Grass: 2,
  Asphalt: 3,
  Pavement: 4,
  Brick: 5,
  BrickDark: 6,
  Roof: 7,
  Water: 8,
  Silt: 9,
  Rubble: 10,
  Wood: 11,
  Moss: 12,
  Concrete: 13,
  Leaves: 14,
} as const;

export type BlockId = (typeof Block)[keyof typeof Block];
export const BLOCK_COUNT = 15;

function rgb(hex: number): [number, number, number] {
  return [((hex >> 16) & 0xff) / 255, ((hex >> 8) & 0xff) / 255, (hex & 0xff) / 255];
}

/** Base albedo per block id (linear-ish sRGB triplets; face shading applied at mesh time). */
export const BLOCK_COLOR: ReadonlyArray<[number, number, number]> = [
  rgb(0x000000), // Air (never rendered)
  rgb(0x7a6a55), // Soil — silt brown
  rgb(0x6fa24b), // Grass — moss green
  rgb(0x9a9591), // Asphalt — bleached
  rgb(0xb8b2a7), // Pavement — weathered concrete
  rgb(0x8c4a32), // Brick — rust
  rgb(0x6e3b2a), // BrickDark
  rgb(0x524b46), // Roof — dark weathered slate/tile
  rgb(0x3e8e7e), // Water — algae teal
  rgb(0x8a7a62), // Silt — pale riverbed
  rgb(0xa8a29a), // Rubble — broken concrete
  rgb(0x7a5c3e), // Wood
  rgb(0x7da65b), // Moss — wall growth, slightly brighter than grass
  rgb(0xb8b2a7), // Concrete
  rgb(0x8fa34f), // Leaves — lichen chartreuse leaning green
];

/** Grass/soil columns get a grass-colored top but soil-colored sides. */
export const BLOCK_TOP_COLOR: ReadonlyArray<[number, number, number] | null> = new Array(BLOCK_COUNT).fill(null);
(BLOCK_TOP_COLOR as Array<[number, number, number] | null>)[Block.Grass] = rgb(0x6fa24b);
(BLOCK_COLOR as Array<[number, number, number]>)[Block.Grass] = rgb(0x7a6a55); // grass sides read as soil

/** Solid for collision purposes (water is swimmable, not solid). */
export function isSolid(id: number): boolean {
  return id !== Block.Air && id !== Block.Water;
}

/** Opaque for meshing purposes (faces against non-opaque neighbors are emitted). */
export function isOpaque(id: number): boolean {
  return id !== Block.Air && id !== Block.Water;
}

/** Directional light baked into vertex colors: +Y bright, sides mid, -Y dark. */
export const FACE_SHADE: Readonly<Record<string, number>> = {
  py: 1.0,
  ny: 0.5,
  px: 0.78,
  nx: 0.72,
  pz: 0.86,
  nz: 0.66,
};
